env:
    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: Sync
  only_if: $CIRRUS_REPO_OWNER == 'MIUI-Kernel'
  timeout_in: 2m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: stupidkidaf/kernel_docker:v1
        cpu: 2
        memory: 4G
  env_script:
    - env
  Sync_script:
      - bash sync.sh
    
task:
  name: "chidori-build"
  only_if: $CIRRUS_REPO_OWNER == 'MIUI-Kernel'
  depends_on:
    - Sync
  timeout_in: 4h
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: stupidkidaf/kernel_docker:v1
        cpu: 24
        memory: 120G
  Build_script:
      - bash build.sh
